title: Mario Wonder Speedrun Guide
description: Test site for SMBW Speedrun Tutorials
theme: just-the-docs

url: https://notCodek.github.io/TestProjectWonderTut

color_scheme: dark

favicon_ico: "/assets/images/favicon.ico"

markdown: kramdown

collections:
  general:
    permalink: "/:collection/:path/"
    output: true

  nmg:
    permalink: "/:collection/:path/"
    output: true

  community:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    general:
      name: General

    nmg:
      name: Any% No Major Glitches

    community:
      name: Community

aux_links:
  "Site Repository": "https://github.com/notCodek/TestProjectWonderTut"
  "Game Leaderboard": "https://www.speedrun.com/smbw"
