title: Florian's Index
description: SMBW Speedrun Resources
theme: just-the-docs

url: https://florians-index.github.io

color_scheme: dark

favicon_ico: "/assets/images/favicon.ico"
logo: "/assets/images/logo.png"

markdown: kramdown

collections:
  general:
    permalink: "/:collection/:path/"
    output: true

  nmg:
    permalink: "/:collection/:path/"
    output: true

  community:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    general:
      name: General

    nmg:
      name: Any% No Major Glitches

    community:
      name: Community

aux_links:
  "Community Discord": "https://discord.gg/kxjxDKu4QX"
  "Game Leaderboard": "https://www.speedrun.com/smbw"
