title: Mario Wonder Speedrun Guide
description: Test site for SMBW Speedrun Tutorials
theme: just-the-docs

url: https://notCodek.github.io/TestProjectWonderTut

color_scheme: dark

aux_links:
  Site Repository: https://github.com/notCodek/TestProjectWonderTut
